apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: saihandson/java-web-app:latest
    ports:
    - containerPort: 8080
