apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapppod
  labels:
    name: mavenapp
spec:
  containers:
  - name: mavenwebappcontainer
    image: saihandson/maven-web-app:25
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappservice
spec:
  type: NodePort
  selector:
          name: mavenapp
  ports:
  - port: 80
    targetPort: 8080
