apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
  name: springboothpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springbootdeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 50
    type: Resource
  
