apiVersion: apps/v1
kind: Deployment
metadata: 
  name: springbootdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      name: springbootpod
      labels:
        app: springbootapp
    spec: 
      containers: 
      - name: springappcontainer
        image: saihandson/springboot-mongo:9
        ports:
        - containerPort: 8080
        env: 
        - name: MONGO_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: MONGO_DB_HOSTNAME
        - name: MONGO_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secreate
              key: username
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secreate
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "25Mi"
          limits:
            cpu: "100m"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
spec: 
  type: NodePort
  selector:
    app: springbootapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: mongorc
spec:
  selector:
    app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec: 
      containers:
      - name: mongocontainer
        image: mongo
        ports:
        - containerPort: 27017
        env: 
        - name:  MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secreate
              key: username
        - name:  MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secreate
              key: password
        volumeMounts:
        - name: mongovol
          mountPath: /data/db
      volumes:
      - name: mongovol
        persistentVolumeClaim:
          claimName: mongopvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app:  mongo
  ports:
  - port: 27017
    targetPort: 27017
        
  
